[package]
name = "xg_sys"
version = "0.7.0"

edition = "2021"



[dependencies]
# xgboost deps
derive_builder = "0.11"
indexmap = "1.9.1"
libc = "0.2"
ndarray="0.15.6"
xgboost_sys = { path = "src/xgboost_sys"}
log = "*"
tempfile = "*"

